version: "3"
services:
  database:
    image: postgres:alpine
    environment:
      POSTGRES_USER: messaging
      POSTGRES_DB: messaging_test
      POSTGRES_PASSWORD: ""
    ports:
      - "5432:5432"
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
  elasticsearch:
    image: elasticsearch:6.7.0
    ports:
      - "9200:9200"
      - "9300:9300"
